### PR TITLE
script to download the assets from github releases

### PR DESCRIPTION
**Pull request by harshad16**
The scripts requires environment variables:
REPO=<repository name> (ex: 'AICoE')
DATE=<date_in_ISO_format> (ex: '2018-07-28')

The scripts would download assets of each release in the local file directory which are released after the DATE.

### CODE REVIEW

**Comment by sub-mod** [comment]
going to close this.Since we have a new approach to do commits.

**Comment by sub-mod** [comment]
remove Pipfile and add required libs in dockerfile

**Comment by goern** [comment]
1. I dont see where they get added to the Dockerfile
2. why not as a Pipfile?

**Comment by harshad16** [comment]
Closing the PR. As we are no longer using this, but using the same functionality through httpd assemble script from https://github.com/harshad16/httpd-aicoe-container/blob/master/2.4/s2i/bin/assemble.
@sub-mod @goern

**Pull request closed without merging**
